### ISSUE TITLE
IFS not reset after reading yaml

### ISSUE THREAD

**Issue by ipa-srd-rd** [ipa320/setup_cob4#207]
As far as I can tell the internal field separator (IFS) is not reset to a space `IFS=" "` after being set to ` IFS="="` for reading in a yaml file (lines 261/271). The hostnames list is however looped through afterwards which doesn't work anymore in case there are more than one host in the list. 

In my opinion the IFS has to be reset to ` IFS=" "` right after reading the yaml. I don't really know how it currently works without causing problems on cobs with multiple pc's, maybe there exists a local fix already.

File: [(https://github.com/ipa320/setup_cob4/blob/master/scripts/cob-command)]

**Comment by ipa-bnm** [comment]
Right, I think so too. But somehow it is working on our robots and this part of the script has not been touched since 4 months. If IFS needs be resetted, then why is it set within a for loop? See [here](https://github.com/ipa320/setup_cob4/blob/master/scripts/cob-command#L271).
@ipa-srd-rd can you please prepare a PR with a solution? We can test this then.

**Comment by ipa-fxm** [comment]
@ipa-srd-rd @ipa-bnm 
any update on this? has a pr been sent/merged?

**Comment by ipa-fxm** [comment]
This issue was moved to mojin-robotics/setup_cob4#7
